[build-system]
requires = ["setuptools", "wheel", "torch"]
build-backend = "setuptools.build_meta"

[project]
name = "custom_rasterizer"
version = "0.1"
requires-python = ">=3.7"
dependencies = ["torch"]